### ISSUE TITLE
lil-gui retaining focus on Windows?

### ISSUE THREAD

**Issue by dboddy** [georgealways/lil-gui#136] opened 2024-03-18 11:48 UTC
Hi, 

My main js module has the following:

`window.addEventListenter('keydown', onKeyDown, false);`

I have noticed that after either:

* un/ticking a checkbox in my lil-gui
*entering a value into text field

...this event no longer fires; I have to do some other interaction in my webpage (e.g. showing / hiding an item such as my custom tree-view) before it once again will detect a `keydown` event.

It seems as though lil-gui retains focus even after clicking back onto the webpage.  For example, if I:

* Select a text input in lil-gui
* Enter any value
* Click back on the webpage (i.e. outside of the lil-gui window)

...then any key I press (which I would expect to be handled by `onKeyDown()`) actually appears in the lil-gui text input field

The issue is occurring on Windows 10 version 22H2 (we use at work), though my home version (on Mac High Sierra!) does not have this problem.

Regards

**Comment by georgealways** [comment] 2024-03-19 03:13
Hi there,

So this is partially intended behavior. All controllers are supposed to stop the propagation of keypress events while they have focus: https://github.com/georgealways/lil-gui/blob/ad90324c1f693c2704fd62b076f090d002ccfbf5/src/Controller.js#L82-L84

The point is to prevent someone from, say, triggering global WASD controls while typing in a text field. But I'm surprised to hear that the events are still being captured after clicking elsewhere (and only on Windows?)
 
For the time being you could comment out those lines, but I recall there being some conversation around making this behavior optional. (https://github.com/georgealways/lil-gui/issues/69)

Thanks for flagging this.

**Comment by dboddy** [comment] 2024-03-21 09:01
Hi, 

Many thanks for your reply.  Your suggestion of commenting out those 2 line has resolved the issue for me, so that's great - thanks.

**Comment by AlaricBaraou** [comment] 2024-05-14 12:19
Just a comment to share that I'm experiencing the same issue. 
A click on a button will retain focus ( this is normal native behavior ) and same with an input etc. 
But once these have the focus, if your page have nothing else to focus on click ( mine just have a canvas ), the focus will remain on those elements and we lose all event listeners that rely on keydown, keyup.

Removing focus when clicking on anything else than the currently focused element fix that.

```
  // make lil-gui clear focus and resume keydown keyup events
  document.addEventListener('click', function(event) {
      // Get the currently focused element
      const focusedElement = document.activeElement;

      // Check if the click target is not the focused element and if there is a focused element
      if (focusedElement && focusedElement !== event.target && !focusedElement.contains(event.target)) {
          // Blur the focused element
          focusedElement.blur();
      }
  });
```

But ideally these two lines shouldn't be used outside of gui elements that requires keyboard interaction.
```
// linit to text input maybe ? Or make this an option ? 
this.domElement.addEventListener( 'keydown', e => e.stopPropagation() ); 
this.domElement.addEventListener( 'keyup', e => e.stopPropagation() ); 
```

Hopes this helps, thank you for this lib!

**Comment by georgealways** [comment] 2024-05-19 15:17
Thanks for your comment @AlaricBaraou. I think a future version of lil-gui will likely include some flag like `new GUI({ stopPropagation: false })`. It would allow the user to manage event propagation manually.

I'm not able to reproduce the following however:

> But once these have the focus, if your page have nothing else to focus on click ( mine just have a canvas ), the focus will remain on those elements and we lose all event listeners that rely on keydown, keyup.

Clicking elsewhere when a form element is focused should cause that element to blur automatically. Testing here: https://lil-gui.georgealways.com/examples/basic

But yes, I think the issue has come up enough that there should be a flag.

**Comment by AlaricBaraou** [comment] 2024-05-19 16:50
@georgealways Apologies, it looks like you're right. I found the cause in my test environment, one of my other lib had a preventDefault() on the event where I was clicking, which would prevent the blur from happening. 

I withdraw what I said. Sorry for the misinformation.

**Comment by georgealways** [comment] 2024-08-04 14:35
@dboddy Did you ever arrive at the cause of this issue? I still don't know why the stopPropagation function would continue to fire after clicking off the GUI, and I'm beginning to wonder if a `captureKeys` flag is necessary. Is it possible that it's caused by something like what @AlaricBaraou encountered above?

**Comment by michael-erskine** [comment] 2024-09-11 08:14
Back when I was using Dat GUI I recall I had to trap events and filter accordingly using a function such as...

```
function isInputEvent (event) {
  const target = event.target
  return (target.tagName === 'INPUT' ||
      target.tagName === 'SELECT' ||
      target.tagName === 'TEXTAREA' ||
      target.isContentEditable)
}
```
Anyhow, I look forward to a workaround going into a release. がんばってください！

**Comment by georgealways** [comment] 2024-09-29 14:43
@michael-erskine The above code hasn't been necessary in lil-gui since 0.15 — controllers call stopPropagation by default, so you don't have to write that anymore.

**Comment by georgealways** [comment] 2024-09-29 14:48
Hi all — closing this and related issues. I went down an overly complex path reacting to this bug and I can't actually reproduce it. Decision and behavior described here: https://github.com/georgealways/lil-gui/pull/138#issuecomment-2381385272

**Closed by georgealways** 2024-09-29 14:48 UTC
